FROM udosson/udosson:chaincode-marbles


# Install additional packages
RUN apk add --no-cache \
	libltdl \
	rsync \
	nano \
	joe \
	less \
    p7zip \
    busybox-extras

# Fix permissions


 

EXPOSE 30111
CMD ./chaincode