apiVersion: v1
kind: Template
metadata:
  name: fabric-orderer-service-deploy
  annotations:
    description: A service which provides a public IP address to acces the Hyperledger Orderer.
    tags: hyperledger,Fabric,Orderer,fabric-orderer,peer,service

labels:
  createdBy: fabric-orderer-template

parameters:
- name: APPLICATION_NAME
  value: 
  required: true
  displayName: Application name
  description: The name for the application. The service will be named like the application.

objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-open
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  spec:
    ports:
    - name: 30110-tcp
      port: 30110
      protocol: TCP
      targetPort: 30110
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    sessionAffinity: None
    type: LoadBalancer
    clusterIP: 
    externalTrafficPolicy: Cluster
